### PR TITLE
Improvements for loot for general quests

### PR DESCRIPTION
**Pull request by musictopia**
Nerfs for general guardians and improvements for general quests to more closely match what the original was.

### CODE REVIEW

**Comment by Ryddag** [comment]
For "<rewardLevel min="0" max="4"> " change are not good, epic chance need to be all to 0, this table is only for first Tuto quest (their is no gear epic at lvl 1 and also we don't want player to loot best adv or design ... at first chest).

If not change seem good if you can just revert this one.

**Comment by musictopia** [comment]
I modified the pull request.  Let me know if I have to delete pull request and start over or not.  Or you can access my fork for the changes.  Thanks to the information given, level 1 chests has been nerfed even further than original.  I remember when doing the quests in the game, the guardians for the level 1 quests only gave materials and maybe sometimes consumables.  I even have that as only common or uncommon, no rare or epic.

**Comment by musictopia** [comment]
Looks like there are a few commits.  The latest one for the nugget, hopefully you can consider that.  Even the one you had, players can still decide to just repeat the level 1 quest to try to get advisors.  I do know for a fact a player cannot get advisors from a level 1 quest.  I even have a suggestion of having a seperate table for levels 1 through 5 for quests.

**Comment by KevinW1998** [comment]
I've reviewed it again and for me it is 👍

**Pull request merged**
